version: "3"

vars:
  AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID
  FUNCTION_NAME: sessionTest
  ZIP_FILE: sessionTest.zip

tasks:
  compile:
    internal: true
    sources:
      - ../**/*
    generates: 
      - sessiontest-lambda/bootstrap
    cmds:
      - |
        GOOS=linux GOARCH=arm64 go build -tags lambda.norpc -o bootstrap main.go
        zip '{{.ZIP_FILE}}' ./bootstrap
  deploy:
    cmds:
      - task: compile
      - |
        cd ../../tf/aws-lambda/session-test
        terraform apply
